#!/opt/clusterware/opt/ruby/bin/ruby

# Script which prints line with each argument followed by stdin.

ARGV.each do |arg|
  puts arg
end

# Clear ARGV so ARGF reads stdin instead of interpreting ARGV as filenames
# (suggested here: http://stackoverflow.com/a/34906353).
ARGV.clear

puts ARGF.read
